version: 2
branches:
  ignore:
    - master
defaults: &defaults
  working_directory: ~/react-graph-me
  docker:
    - image: circleci/node:8.12.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-graph-me
      #- restore_cache: # npm ci does a clean of node_modules
      #    key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: npm i gulp
          command: npm i gulp@3.9.1
      #- save_cache: # npm ci does a clean of node_modules
      #    key: dependency-cache-{{ checksum "package.json" }}
      #    paths:
      #      - ./node_modules
      - run:
          name: gulp bundle
          command: node_modules/.bin/gulp bundle --ship
      - run:
          name: gulp package-solution
          command: node_modules/.bin/gulp package-solution --ship
      - persist_to_workspace:
          root: .
          paths: ["./sharepoint/solution/*"]
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-graph-me
      - run:
          name: Test Run All
          command: npm run test
    #   - run:
    #       name: Test React
    #       command: npm run test-react
    #   - run:
    #       name: Test Handlebars
    #       command: npm run test-handlebars
      - store_artifacts:
          path: testresult
workflows:
  version: 2
  testing:
    jobs:
      - build:
          filters:
            branches:
              only: integration
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: dev
